dist: trusty
sudo: required
language: node_js

services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build dternyak/eth-priv-to-addr:latest

install:
  - npm install --silent

script:
- npm run test
- npm run int-test
- npm run tslint
- npm run tscheck
- npm run freezer
- npm run freezer:validate

notifications:
  email:
    on_success: never
    on_failure: never